Feature/create typed config function
cashwalk/nestjs-typed-config pull request #2
Opened 2023-09-19 08:20 UTC by leejs1030-cashwalk

2023-09-20 06:20 UTC, backend-seunggeun commented on src/index.ts
> +  BaseTypedConfigService,
이제 이건 export 할 필요가 없지 않을까요?

2023-09-20 06:20 UTC, backend-seunggeun commented on src/index.ts
> +  BaseTypedConfigService,
하위 호환성을 만족하기 위해서라면, 아직 버전이 0 버전이니 만족을 안 해도 될 것 같습니다

2023-09-20 06:21 UTC, leejs1030-cashwalk commented on src/index.ts
> +  BaseTypedConfigService,
오 넵 호환때문에 그런거였는데 그러면 과감하게 버리도록 하겠습니다

2023-09-20 06:21 UTC, backend-seunggeun requested changes
아주 간단한 example 앱이 있으면 어떨까요?

2023-09-20 06:25 UTC, leejs1030-cashwalk commented
오 넵 examples/ 폴더로 하나 파서 해보겠습니다

2023-09-21 04:35 UTC, backend-seunggeun commented on src/index.ts
> +  BaseTypedConfigService,
0 버전이어서 일단 지울 거 지우고 심플하게 가는 게 좋을 것 같아요

2023-09-21 23:42 UTC, leejs1030-cashwalk commented
다른 pr로 example 생성하겠습니다

2023-09-21 23:42 UTC, merged